import type { Metadata } from "next";

import "./globals.css";
import ReduxProvider from "@/providers/reduxProvider";




export const metadata: Metadata = {
  title: "A2SV Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
        {children}
        </ReduxProvider>
  
      </body>
    </html>
  );
}
